### ISSUE TITLE
Incompatibility issues

### ISSUE THREAD

**Issue by HassaanBG** [MicrocontrollersDev/Sciophobia#1]
The mod isn't compatible with some older versions like 1.19.2, I Would really appreciate if u back port the mod to 1.19.2.

**Comment by MicrocontrollersDev** [comment]
if I do a backport, there will be no config option. the mod will always be enabled. the issue is YACL (my config library) no longer receives updates. it is certainly something I can do though

**Comment by HassaanBG** [comment]
Okay ;v
